plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-performance

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false
Layout/LineLength:
  Max: 120
Lint/MissingSuper:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
RSpec/ImplicitExpect:
  EnforcedStyle: is_expected
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 6
