services:
  app:
    build:
      network: host
      target: development
      tags:
        - book-reviews:0.1
    container_name: book-reviews-app
    image: book-reviews:0.1
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www
      - bundle_cache:/bundle
      - node_modules_cache:/var/www/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: book-reviews-db
    image: postgres:latest
    volumes:
      - postgresql_cache:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  bundle_cache:
  node_modules_cache:
  postgresql_cache:
